module Sasync
  packages="com.opsware.acm
  com.opsware.apx
  com.opsware.atm
  com.opsware.busapp
  com.opsware.cache
  com.opsware.client
  com.opsware.client.security
  com.opsware.client.smo
  com.opsware.common
  com.opsware.compliance
  com.opsware.compliance.sco
  com.opsware.compliance.sco.policy
  com.opsware.custattr
  com.opsware.device
  com.opsware.fido
  com.opsware.fido.apx
  com.opsware.folder
  com.opsware.job
  com.opsware.locality
  com.opsware.nas
  com.opsware.osprov
  com.opsware.pkg
  com.opsware.pkg.aix
  com.opsware.pkg.hpux
  com.opsware.pkg.solaris
  com.opsware.pkg.windows
  com.opsware.report
  com.opsware.reportresult
  com.opsware.savedsearch
  com.opsware.script
  com.opsware.search
  com.opsware.server
  com.opsware.shared
  com.opsware.sitemap
  com.opsware.smo
  com.opsware.storage
  com.opsware.storage.netapp
  com.opsware.streamable
  com.opsware.swmgmt
  com.opsware.swmgmt.ismcontrol
  com.opsware.system.recert
  com.opsware.unitio
  com.opsware.virtualization
  com.opsware.virtualization.microsoft
  com.opsware.virtualization.solaris
  com.opsware.virtualization.vmware".lines.map(&:strip)
  packages.each do |pkg|
    include_package "#{pkg}"
  end
end