//These are definitions for models for SAS Objects in EXT
//Mainly listed here for informational purposes.
Ext.define('ServerVO', {
    extend: 'Ext.data.Model',
    fields: [
        'class_name',
        'short_host_name',
        'name',
        'state',
        'locale',
        'realm',
        'use',
        'platform',
        'mid',
        'agentVersion',
        'stage',
        'opswLifecycle',
        'defaultGw',
        'hypervisor',
        'osFlavor',
        'virtualizationType',
        'customer',
        'facility',
        'discoveredDate',
        'loopbackIP',
        'managementIP',
        'netBIOSName',
        'peerIP',
        'reporting',
        'osSPVersion',
        'previousSWRegDate',
        'hostName',
        'description',
        'osVersion',
        'serialNumber',
        'primaryIP',
        'manufacturer',
        'model',
        'modifiedBy',
        'modifiedDate',
        'logChange',
        'createdBy',
        'createdDate'
    ]
})